// src/lib/vatican-borgia.ts
//
// Accessors for the Vatican Library's Borgia Tonchinensis fond, mirroring
// src/lib/pennstate-edicts.ts.
//
// Two sources feed this collection and they are kept apart on purpose:
//
//   * VaticanBorgiaMetadata.ts is what the Vatican publishes — shelfmark, page
//     count, IIIF URLs — regenerated by the fetch script.
//   * vatican-borgia-descriptions.ts is what DVN writes, because the Vatican
//     catalogues this fond as shelfmark-only records with no titles at all.
//
// This module joins the two and gives the pages a single shape to render.

import {
  VATICAN_BORGIA_ITEMS,
  type VaticanBorgiaRecord,
} from "@/app/[locale]/our-collections/VaticanBorgiaMetadata";
import { BORGIA_DESCRIPTIONS } from "@/lib/vatican-borgia-descriptions";
import { normalizeSearchText } from "@/lib/utils";

/** Slug this collection lives at, and the slug its Strapi record uses. */
export const BORGIA_COLLECTION_SLUG = "the-borgia-tonchinensis-collection";

/**
 * Provenance for the fond. The Vatican asserts copyright over these images and
 * its terms forbid reproduction without authorisation; DVN presents them by
 * permission of the Vatican Digital Library, which is what the credit says.
 */
export const VATICAN_REPOSITORY = {
  label: "Biblioteca Apostolica Vaticana",
  labelEn: "Vatican Library",
  labelVi: "Thư viện Vatican",
  digitalLibrary: "Vatican Digital Library (DigiVatLib)",
  digitalLibraryVi: "Thư viện Số Vatican (DigiVatLib)",
  url: "https://digi.vatlib.it/",
  fondUrl: "https://digi.vatlib.it/mss/Borg.tonch",
  /** The Vatican's own attribution string, as it appears in their manifests. */
  attribution: "Images Copyright Biblioteca Apostolica Vaticana",
  extent: "41 items",
  dateRange: "17th–19th century",
} as const;

export type BorgiaEntry = VaticanBorgiaRecord;

/** Shelfmark order — the order the fond itself is arranged in. */
export const getBorgiaEntries = (): BorgiaEntry[] =>
  [...VATICAN_BORGIA_ITEMS].sort((a, b) => a.sequence - b.sequence);

export const getBorgiaByItemId = (itemId: string): BorgiaEntry | undefined =>
  VATICAN_BORGIA_ITEMS.find((entry) => entry.itemId === itemId);

export const getBorgiaDescription = (entry: BorgiaEntry) =>
  BORGIA_DESCRIPTIONS[entry.shelfmark];

/**
 * Heading and summary in the reader's language.
 *
 * Falls back to the shelfmark, which is all the Vatican itself shows, so an
 * uncatalogued volume still has a usable title rather than an empty heading.
 */
export const getBorgiaText = (entry: BorgiaEntry, locale: string) => {
  const description = getBorgiaDescription(entry);
  const vi = locale === "vi";

  // DVN catalogued this fond in Vietnamese first. Rather than leave an English
  // reader with a bare shelfmark, fall back to the Vietnamese and let the page
  // say which language it is showing.
  const pick = (text?: { vi: string; en?: string }) => {
    if (!text) return { value: "", isVietnameseFallback: false };
    if (vi) return { value: text.vi, isVietnameseFallback: false };
    return text.en
      ? { value: text.en, isVietnameseFallback: false }
      : { value: text.vi, isVietnameseFallback: true };
  };

  const title = pick(description?.title);
  const summary = pick(description?.summary);

  return {
    title: title.value || entry.shelfmark,
    summary: summary.value,
    /**
     * True only when the SUMMARY falls back. A Vietnamese title needs no such
     * note — these are Vietnamese works, and "Truyện nước Annam" is the name of
     * the book in either language.
     */
    isVietnameseFallback: summary.isVietnameseFallback,
    /** False while a volume is still shelfmark-only, as the Vatican leaves it. */
    isCatalogued: Boolean(title.value),
  };
};

/** "1.392 trang" / "1,392 pages" — page counts here run into four figures. */
export const formatPageCount = (pageCount: number, locale: string) => {
  const formatted = pageCount.toLocaleString(locale === "vi" ? "vi-VN" : "en-US");
  return locale === "vi" ? `${formatted} trang` : `${formatted} pages`;
};

/**
 * The haystack a free-text query is matched against: the shelfmark plus
 * whatever DVN has catalogued, in both locales, so a Vietnamese search term
 * finds a volume described in English and the other way round.
 */
export const getSearchHaystack = (entry: BorgiaEntry) => {
  const description = getBorgiaDescription(entry);
  return normalizeSearchText(
    [
      entry.shelfmark,
      entry.label,
      description?.title?.en,
      description?.title?.vi,
      description?.summary?.en,
      description?.summary?.vi,
      description?.genre,
      description?.century,
      description?.scripts?.join(" "),
    ]
      .filter(Boolean)
      .join(" ")
  );
};

export const borgiaMatchesQuery = (entry: BorgiaEntry, query: string) => {
  const trimmed = (query ?? "").trim();
  if (!trimmed) return true;
  return getSearchHaystack(entry).includes(normalizeSearchText(trimmed));
};
